TABLE_SCHEMAS = {
    "acctian_lo_stl_purpose.trl": {
        "table_type": "audit",
        "base_table": "lo_stl_purpose",
        "stride": 337,
        "columns": [
            "purpose_code",
            "purpose_description",
            "loan_type_code",
        ],
        "primary_key": [
            "purpose_code",
            "loan_type_code",
        ],
    },

    "lo_stl_frontend.trl": {
        "table_type": "transaction",
        "base_table": "lo_stl_frontend",
        "stride": 1311,
        "columns": [
            "loan_id",
            "loan_type",
            "member_no",
            "member_no_alt",
            "employer_id",
            "process_time",
            "last_name",
            "first_name",
            "middle_name",
            "branch_code",
            "hub_code",
            "area_code",
            "loan_status",
            "scheme_code",
            "purpose_code",
            "release_mode",
            "gross_amount",
            "deductions",
            "net_amount",
            "process_branch",
        ],
        "primary_key": ["loan_id"],
    },

    "lo_stl_online_application.trl": {
        "table_type": "transaction",
        "base_table": "lo_stl_online_application",
        "stride": 1119,
        "columns": [
            "loan_id",
            "app_ref_no",
            "member_no",
            "last_name",
            "first_name",
            "middle_name",
            "email",
            "mobile_no",
            "loan_type",
            "term_months",
            "account_no",
            "employer_id",
            "branch_code",
            "status",
            "purpose_code",
        ],
        "primary_key": ["loan_id"],
    },

    "lms_noncash_collection.trl": {
        "table_type": "transaction",
        "base_table": "lms_noncash_collection",
        "stride": 517,
        "columns": [
            "collection_id",
            "member_no",
            "loan_id",
            "collection_type",
            "amount_code",
            "batch_ref",
            "branch_code",
        ],
        "primary_key": ["collection_id"],
    },

    "lms_stl_disbursement_master.trl": {
        "table_type": "transaction",
        "base_table": "lms_stl_disbursement_master",
        "stride": 471,
        "columns": [
            "disbursement_id",
            "batch_id",
            "batch_id_alt",
            "borrower_name",
            "process_time",
            "branch_code",
            "processed_by",
        ],
        "primary_key": ["disbursement_id"],
    },

    "pf_employer_master.trl": {
        "table_type": "transaction",
        "base_table": "pf_employer_master",
        "stride": 1414,
        "columns": [
            "employer_id_raw",
            "employer_id",
            "employer_id_alt",
            "tin_no",
            "branch_code",
            "employer_type",
            "employer_name",
            "address",
            "contact_no",
            "fax_no",
            "employer_short_name",
            "employee_count",
            "mobile_no",
            "city_code",
            "status_code",
            "region_code",
        ],
        "primary_key": ["employer_id"],
    },
}


RISK_01_FILES = {
    "hdmf_branches.trl",
    "hdmf_hub_master.trl",
    "lms_transaction_status.trl",
    "lo_stl_bank_master.trl",
    "lo_stl_release_mode.trl",
    "lo_stl_scheme_master.trl",
    "membership_category.trl",
}
